Add warning messages for generate features generating to source dir
OpenLiberty/ci.common pull request #377
Opened 2022-06-09 15:17 UTC by kathrynkodama

Toggling generate features on after dev mode as started:
```
h
[INFO] ************************************************************************
[INFO] *        Automatic generation of features: [ Off ]
[INFO] *        g - toggle the automatic generation of features, type 'g' and press Enter. A new server configuration file will be generated in the SOURCE configuration directory.
[INFO] *        Enter - run tests on demand, press Enter.
[INFO] *        r - restart the server, type 'r' and press Enter.
[INFO] *        h - see the help menu for available actions, type 'h' and press Enter.
[INFO] *        q - stop the server and quit dev mode, press Ctrl-C or type 'q' and press Enter.
[INFO] ************************************************************************
g
[INFO] Setting automatic generation of features to: [ On ]
[WARNING] The source configuration directory will be modified. Features will automatically be generated in a new file: /Users/kathrynkodama/devex/sampleProjects/demo-devmode/src/main/liberty/config/configDropins/overrides/generated-features.xml
[INFO] Running liberty:generate-features
[INFO] Regenerated the following features: [cdi-2.0, mpMetrics-3.0, jaxrs-2.1]
```

Starting dev mode with `generateFeatures=true`:
```
[WARNING] The source configuration directory will be modified. Features will automatically be generated in a new file: /Users/kathrynkodama/devex/sampleProjects/demo-devmode/src/main/liberty/config/configDropins/overrides/generated-features.xml
[INFO] Running liberty:generate-features
[INFO] Regenerated the following features: [cdi-2.0, mpMetrics-3.0, jaxrs-2.1]
[INFO] Running liberty:create
...

h
[INFO] ************************************************************************
[INFO] *        Automatic generation of features: [ On ]
[INFO] *        g - toggle the automatic generation of features, type 'g' and press Enter. A new server configuration file will be generated in the SOURCE configuration directory.
[INFO] *        o - optimize the list of generated features, type 'o' and press Enter. A new server configuration file will be generated in the SOURCE configuration directory.
[INFO] *        Enter - run tests on demand, press Enter.
[INFO] *        r - restart the server, type 'r' and press Enter.
[INFO] *        h - see the help menu for available actions, type 'h' and press Enter.
[INFO] *        q - stop the server and quit dev mode, press Ctrl-C or type 'q' and press Enter.
[INFO] ************************************************************************

```
Signed-off-by: Kathryn Kodama <kathryn.s.kodama@gmail.com>

2022-06-09 21:27 UTC, TrevCraw reviewed
We discussed showing the warning only once. We seemed to be leaning that direction so maybe we should add a flag here to track that we only display one time.

2022-06-09 21:51 UTC, yeekangc requested changes

2022-06-09 21:51 UTC, yeekangc commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                "g - toggle the automatic generation of features, type 'g' and press Enter. A new server configuration file will be generated in the SOURCE configuration directory."));
Can we indicate that it will be a dropin config?

2022-06-09 21:51 UTC, yeekangc commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +            info(formatAttentionMessage("o - optimize the list of generated features, type 'o' and press Enter. A new server configuration file will be generated in the SOURCE configuration directory
Can we indicate it will be a dropin config (that adds to any existing config)?

2022-06-09 21:53 UTC, yeekangc requested changes
Please consider my comments.

2022-06-12 22:26 UTC, turkeylurkey commented
I think it is ok to print the message each time you toggle it on. That should not happen very often. Just don't show it every time you save a file.

2022-06-13 14:40 UTC, kathrynkodama commented
@TrevCraw @turkeylurkey I agree with Paul that it makes sense to show the warning each time we toggle feature generation on. It will not be shown each time feature generation runs (only when toggled on) and on startup if `generateFeatures=true`.

2022-06-13 15:41 UTC, yeekangc commented
+1 to show the warning every time feature generation is turned on.

2022-06-13 15:42 UTC, yeekangc approved these changes

2022-06-13 15:47 UTC, TrevCraw approved these changes

2022-06-13 16:02 UTC, merged