Server multi restart issue fix
OpenLiberty/ci.common pull request #466
Opened 2024-12-23 04:49 UTC by arunvenmany-ibm

2025-01-08 17:46 UTC, cherylking requested changes

2025-01-08 17:46 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                   String mavenCacheLocation, List<ProjectModule> upstreamProjects, boolean recompileDependencies,
Why not provide a second constructor without the Map since Gradle does not need it? Then when that constructor is used, you could initialize the Map to an empty Map instead of making the Gradle code do that.

2025-01-08 17:46 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                    triggerUpstreamModuleCompile(project, false);
Once this compile is triggered for the project that had TRUE in the projectRecompileMap, does something remove it from the Map or set it to FALSE?

2025-01-09 06:59 UTC, arunvenmany-ibm commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                    triggerUpstreamModuleCompile(project, false);
No. we are only using this map at the beginning of initWatchLoop() , just to skip the recompilation there.
Whenever there is file change , processFileChanges() is triggered, which triggers triggerProjectCompile() method separately.

2025-01-09 08:19 UTC, arunvenmany-ibm commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                   String mavenCacheLocation, List<ProjectModule> upstreamProjects, boolean recompileDependencies,
Done

2025-01-09 13:44 UTC, cherylking requested changes

2025-01-09 13:44 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                if (projectRecompileMap.isEmpty() || Boolean.TRUE.equals(projectRecompileMap.get(project.getProjectName())) ) {
When exactly can the map be empty? 1) When called from Gradle? If so, the `info` message at 4054 may be misleading? 2) When no project was identified as needing to be recompiled in Maven? If so, why would we do a recompile here?

2025-01-09 13:44 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +        if (projectRecompileMap.isEmpty()|| Boolean.TRUE.equals(projectRecompileMap.get(getProjectName())) ) {
Same comment about what an empty projectRecompileMap means and how it should affect the `info` messages.

2025-01-10 02:42 UTC, arunvenmany-ibm commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                if (projectRecompileMap.isEmpty() || Boolean.TRUE.equals(projectRecompileMap.get(project.getProjectName())) ) {
Map can be empty when passed from gradle. 
Gradle is already using Gradle task state to check whether a recompile is required. Hence even if we always trigger compile from our end, it just returns task state as EVERYTHING UP-TO-DATE

2025-01-10 03:56 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                if (projectRecompileMap.isEmpty() || Boolean.TRUE.equals(projectRecompileMap.get(project.getProjectName())) ) {
But can't it also be empty coming from Maven if no projects had compile errors?

2025-01-10 03:57 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                if (projectRecompileMap.isEmpty() || Boolean.TRUE.equals(projectRecompileMap.get(project.getProjectName())) ) {
And since the answer for 1 is yes, my comment about the misleading messages applies.

2025-01-14 05:47 UTC, arunvenmany-ibm commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                if (projectRecompileMap.isEmpty() || Boolean.TRUE.equals(projectRecompileMap.get(project.getProjectName())) ) {
Changed to set projectRecompileMap as null for gradle and updated message

2025-01-14 05:47 UTC, arunvenmany-ibm commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +        if (projectRecompileMap.isEmpty()|| Boolean.TRUE.equals(projectRecompileMap.get(getProjectName())) ) {
Changed to set projectRecompileMap as null for gradle and updated message

2025-01-14 20:48 UTC, cherylking requested changes

2025-01-14 20:48 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                    info("Recompile " + project.getProjectName() + " due to an earlier compilation error");
So if we are here for gradle and the map is null, we will print a message saying we are recompiling due to an earlier compilation error. But that may or may not be true, right?

2025-01-15 07:24 UTC, arunvenmany-ibm commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                    info("Recompile " + project.getProjectName() + " due to an earlier compilation error");
Corrected the if else for gradle and maven

2025-01-15 12:41 UTC, cherylking requested changes

2025-01-15 12:41 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                    info("Recompile " + project.getProjectName() + " due to an earlier compilation error");
Ok, why are we triggering a different method for Gradle here? Should it be `triggerUpstreamModuleCompile`? I think we need a Gradle PR pulling in this branch and running tests to ensure everything is good.

Also, shouldn't we log some message like "Check if recompile for project x needs to be done." or just "Recompile project x." and that will get followed up by the typical Gradle message about a task is UP-TO-DATE?

2025-01-15 12:41 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +            triggerMainModuleCompile(false);
I think we need some message here for the gradle scenario.

2025-01-15 13:09 UTC, arunvenmany-ibm commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                    info("Recompile " + project.getProjectName() + " due to an earlier compilation error");
We can trigger triggerUpstreamModuleCompile or triggerMainModuleCompile in case of gradle, because when we trigger a compile in gradle for EAR , it actually checks whether it needs to recompile any dependent modules. 
After some thoughts , I have rolled back to triggerMainModuleCompile

triggerUpstreamModuleCompile() or triggerMainModuleCompile() just adds sourceSet to a map, which is used in recompileJava() 

![image](https://github.com/user-attachments/assets/a61ad404-2cdd-4d19-abbd-4d76befd23f6)
the useBuildRecompile() flag is set as true in gradle and set as false in maven

In case of gradle, it triggers compile() method in ci.gradle DevTask class
I think no custom message is needed in case of gradle, since it just trigger gradle task directly, which gives full info

![image](https://github.com/user-attachments/assets/2bd65fee-4f42-4844-9e60-ee163b2880e0)

2025-01-15 13:17 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                    info("Recompile " + project.getProjectName() + " due to an earlier compilation error");
Think of our log messages as helpful hints when debugging a user issue. In that case, it would be helpful to know why the compile got triggered in Gradle. Are there any other paths into that compile method you show in your last image besides this ci.common method?

If you are going to call a different method here for gradle, please add a comment explaining why.

2025-01-15 13:24 UTC, arunvenmany-ibm commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                    info("Recompile " + project.getProjectName() + " due to an earlier compilation error");
1.
 a. can you provide some wordings for the ci.gradle related message. Since we are not changing anything affecting ci.gradle in any scenarios, I was not sure to introduce a new message.
 b. compile() is being called for any scenario with RecompileJava() -> called from processUpstreamJavaCompilation() in dev file changes

2. No We will keep the triggerUpstreamModuleCompile() itself

2025-01-15 13:39 UTC, arunvenmany-ibm commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                    info("Recompile " + project.getProjectName() + " due to an earlier compilation error");
Yes, gradle task decide what to be done
I will add a log message saying "Recompile {project_name}

2025-01-15 13:46 UTC, cherylking requested changes

2025-01-15 13:46 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
>          lastBuildFileChange.put(buildFile, System.currentTimeMillis());
Sorry I didn't notice this before. Do we really want to update `lastBuildFileChange` if we skip recompile?

2025-01-15 13:52 UTC, arunvenmany-ibm commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
>          lastBuildFileChange.put(buildFile, System.currentTimeMillis());
Since sourceSet is not being added, I think its okay to keep it 
I have added tests for checking recompile in ci.maven

2025-01-17 13:26 UTC, cherylking requested changes

2025-01-17 13:26 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                boolean pastBuildFileWaitPeriod = lastBuildFileChange.get(project.getBuildFile()) != null && System
We want this to be set to true when the map returns null.

2025-01-17 13:26 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                lastBuildFileChange.put(project.getBuildFile(), System.currentTimeMillis());
This should only be set in the if and else if with the change you made to check for null.

2025-01-17 13:48 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                lastBuildFileChange.put(project.getBuildFile(), System.currentTimeMillis());
If you are saying it is needed for our tests to work, then I question how our tests are structured. We should not have code in production that is only for testing purposes.

2025-01-17 14:55 UTC, arunvenmany-ibm commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                lastBuildFileChange.put(project.getBuildFile(), System.currentTimeMillis());
No I am talking about the tests compile invocation, in the processupstreamJavaCompilation(), 
Currently, if there is no change in build file, we are skipping the execution, 
![image](https://github.com/user-attachments/assets/79bb23a2-d58e-4574-a53c-051fdc4709cc)

But I could see that we have more logic for processing test files

![image](https://github.com/user-attachments/assets/a0ba9d27-de35-4c4c-809b-47785b5f336d)

2025-01-17 23:57 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                lastBuildFileChange.put(project.getBuildFile(), System.currentTimeMillis());
If you set `pastBuildFileWaitPeriod` to true when `lastBuildFileChange.get()` returns null, it will work correctly.

2025-01-21 11:45 UTC, arunvenmany-ibm commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                lastBuildFileChange.put(project.getBuildFile(), System.currentTimeMillis());
I tried defaulting pastBuildFileWaitPeriod with both true and false, both scenarios are causing many tests to fail

2025-01-21 18:56 UTC, cherylking commented on src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java
> +                lastBuildFileChange.put(project.getBuildFile(), System.currentTimeMillis());
It seems to be passing with the latest change.

2025-01-21 18:59 UTC, cherylking approved these changes

2025-01-22 03:40 UTC, merged